export const TOOLS = [
  {
    id: 'compress',
    name: 'Compress Image',
    description: 'Reduce image file size while maintaining quality',
    href: '/compress-image',
    icon: 'Minimize2',
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 'resize',
    name: 'Resize Image',
    description: 'Change image dimensions with preset or custom sizes',
    href: '/resize-image',
    icon: 'Maximize2',
    color: 'from-violet-500 to-violet-600',
  },
  {
    id: 'crop',
    name: 'Crop Image',
    description: 'Crop images with free or fixed aspect ratios',
    href: '/crop-image',
    icon: 'Crop',
    color: 'from-cyan-500 to-cyan-600',
  },
  {
    id: 'convert',
    name: 'Convert Image',
    description: 'Convert between JPG, PNG, and WebP formats',
    href: '/convert-image',
    icon: 'RefreshCw',
    color: 'from-emerald-500 to-emerald-600',
  },
  {
    id: 'rotate',
    name: 'Rotate Image',
    description: 'Rotate images 90°, 180°, 270° or custom angle',
    href: '/rotate-image',
    icon: 'RotateCw',
    color: 'from-orange-500 to-orange-600',
  },
  {
    id: 'flip',
    name: 'Flip Image',
    description: 'Flip images horizontally, vertically or both',
    href: '/flip-image',
    icon: 'FlipHorizontal',
    color: 'from-pink-500 to-pink-600',
  },
  {
    id: 'watermark',
    name: 'Watermark Image',
    description: 'Add text watermarks with custom position and style',
    href: '/watermark-image',
    icon: 'Stamp',
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 'metadata',
    name: 'Metadata Viewer',
    description: 'View file name, size, dimensions and format details',
    href: '/metadata-viewer',
    icon: 'Info',
    color: 'from-slate-500 to-slate-600',
  },
] as const
